# version: '3'
# services:
#   web:
#     environment:
#       - CHOKIDAR_USEPOLLING=true
#       - HOST=0.0.0.0
#       - PORT=3000
#     build:
#       context: .
#       dockerfile: dockerfile.dev
#     ports:
#       - "3000:3000"
#     volumes:
#       - .:/app
#       - /app/node_modules
#   tests:
#     stdin_open: true
#     build:
#       context: .
#       dockerfile: dockerfile.dev
#     volumes:
#       - /app/node_modules
#       - .:/app
#     command: ['npm', 'run', 'test']

version: "3"

services:
  web:
    build:
      context: .
      dockerfile: dockerfile.dev
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - HOST=0.0.0.0
      - PORT=3000
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true

  tests:
    build:
      context: .
      dockerfile: dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "run", "test"]
    stdin_open: true
    tty: true
